[package]
name = "neve-store"
description = "Content-addressed store for Neve"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
neve-derive = { version = "4.0.3", path = "../neve-derive" }
neve-fetch = { version = "4.0.3", path = "../neve-fetch" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
flate2.workspace = true
lzma-rs.workspace = true
zstd.workspace = true
tempfile.workspace = true
reqwest.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
