[package]
name = "neve-frontend"
description = "Frontend analysis pipeline for Neve (parse + lower + type check)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
neve-common = { version = "4.0.4", path = "../neve-common" }
neve-diagnostic = { version = "4.0.4", path = "../neve-diagnostic" }
neve-parser = { version = "4.0.4", path = "../neve-parser" }
neve-hir = { version = "4.0.4", path = "../neve-hir" }
neve-syntax = { version = "4.0.4", path = "../neve-syntax" }
neve-typeck = { version = "4.0.4", path = "../neve-typeck" }
