[package]
name = "neve-typeck"
description = "Type checking for Neve"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
neve-common = { version = "4.0.1", path = "../neve-common" }
neve-hir = { version = "4.0.1", path = "../neve-hir" }
neve-diagnostic = { version = "4.0.1", path = "../neve-diagnostic" }

[dev-dependencies]
neve-parser = { version = "4.0.1", path = "../neve-parser" }
