[package]
name = "neve-config"
description = "System configuration and generation management for Neve"
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neve-diagnostic = { version = "4.0.3", path = "../neve-diagnostic" }
neve-frontend = { version = "4.0.3", path = "../neve-frontend" }
neve-eval = { version = "4.0.3", path = "../neve-eval" }
neve-derive = { version = "4.0.3", path = "../neve-derive" }
neve-store = { version = "4.0.3", path = "../neve-store" }
neve-builder = { version = "4.0.3", path = "../neve-builder" }
neve-fetch = { version = "4.0.3", path = "../neve-fetch" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
