fn main() {
    // parser.c is generated by `tree-sitter generate` from grammar.js.
    // It is not checked into the repository. If the file is missing, skip
    // compilation — the binding can still be used for type-checking.
    let src_dir = std::path::Path::new("../../src");
    let parser_c = src_dir.join("parser.c");
    if !parser_c.exists() {
        println!("cargo:warning=parser.c not found — run `tree-sitter generate` to build");
        return;
    }
    let mut c_config = cc::Build::new();
    c_config.include(src_dir);
    c_config
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-but-set-variable")
        .flag_if_supported("-Wno-trigraphs");
    c_config.file(parser_c.to_str().unwrap());
    c_config.compile("tree-sitter-neve");
    println!("cargo:rerun-if-changed={}", parser_c.display());
}
