//! Helix editor setup command.
//! Helix 编辑器设置命令。

use std::fs;
use std::path::PathBuf;
use std::process::Command;

/// Install Neve support for Helix editor.
/// 为 Helix 编辑器安装 Neve 支持。
pub fn run() -> Result<(), String> {
    let home = dirs().ok_or("cannot find home directory")?;
    let helix_grammar = home.join(".config/helix/runtime/grammars");
    let helix_queries = home.join(".config/helix/runtime/queries/neve");
    let helix_config = home.join(".config/helix/languages.toml");

    fs::create_dir_all(&helix_grammar).map_err(|e| format!("mkdir: {e}"))?;
    fs::create_dir_all(&helix_queries).map_err(|e| format!("mkdir: {e}"))?;

    println!("Setting up Neve for Helix...");

    // 1. Build and install tree-sitter grammar
    let ts_dir = find_tree_sitter_dir()?;
    println!("  Building tree-sitter-neve grammar...");
    let status = Command::new("tree-sitter")
        .args(["build"])
        .current_dir(&ts_dir)
        .status()
        .map_err(|e| {
            format!("tree-sitter not found. Install: cargo install tree-sitter-cli\n{e}")
        })?;

    if !status.success() {
        return Err("tree-sitter build failed".into());
    }

    let so_file = ts_dir.join("neve.so");
    if so_file.exists() {
        fs::copy(&so_file, helix_grammar.join("neve.so"))
            .map_err(|e| format!("copy grammar: {e}"))?;
        println!("  ✓ grammar installed");
    }

    // 2. Install highlights.scm
    let highlights = r#"; Neve syntax highlighting for Helix
[
  "let" "fn" "if" "then" "else" "match" "import" "as"
  "type" "struct" "enum" "trait" "impl" "pub" "effect" "lazy"
] @keyword

(fn_def name: (ident) @function)
(struct_def name: (ident) @type)
(enum_def name: (ident) @type)

(number) @constant.numeric
(string) @string
(comment) @comment
("true") @constant.builtin
("false") @constant.builtin

[ "+" "-" "*" "/" "==" "!=" "<" ">" "|>" "=" "->" ] @operator
[ "(" ")" "[" "]" "{" "}" "," ";" ":" ] @punctuation.delimiter
"#;
    fs::write(helix_queries.join("highlights.scm"), highlights)
        .map_err(|e| format!("write highlights: {e}"))?;
    println!("  ✓ highlights installed");

    // 3. Install languages.toml config
    let config = format!(
        r#"# Neve language support (auto-generated by `neve setup helix`)
[[language]]
name = "neve"
scope = "source.neve"
file-types = ["neve"]
comment-token = "--"
indent = {{ tab-width = 4, unit = "    " }}
language-servers = ["neve-lsp"]
formatter = {{ command = "neve", args = ["fmt", "file", "--write"] }}
auto-format = true

[language-server.neve-lsp]
command = "neve"
args = ["lsp"]
"#
    );

    // Append to existing config or create new one
    let existing = if helix_config.exists() {
        fs::read_to_string(&helix_config).unwrap_or_default()
    } else {
        String::new()
    };

    if !existing.contains("name = \"neve\"") {
        let new_content = if existing.is_empty() {
            config
        } else {
            format!("{existing}\n{config}")
        };
        fs::write(&helix_config, new_content)
            .map_err(|e| format!("write config: {e}"))?;
        println!("  ✓ languages.toml updated");
    } else {
        println!("  • languages.toml already configured");
    }

    println!("\n✅ Neve Helix support installed!");
    println!("   Open any .neve file: hx file.neve");
    Ok(())
}

fn dirs() -> Option<PathBuf> {
    std::env::var("HOME").ok().map(PathBuf::from)
}

fn find_tree_sitter_dir() -> Result<PathBuf, String> {
    // Check common locations
    let candidates = [
        PathBuf::from("tree-sitter-neve"),
        PathBuf::from("/usr/share/neve/tree-sitter-neve"),
    ];

    for c in &candidates {
        if c.join("grammar.js").exists() {
            return Ok(c.clone());
        }
    }

    // Clone from GitHub
    let tmp = std::env::temp_dir().join("neve-tree-sitter");
    if !tmp.exists() {
        println!("  Cloning tree-sitter-neve...");
        let status = Command::new("git")
            .args([
                "clone",
                "https://github.com/MCB-SMART-BOY/Neve",
                tmp.to_str().unwrap(),
                "--depth=1",
                "--filter=tree:0",
                "--sparse",
            ])
            .status()
            .map_err(|e| format!("git: {e}"))?;
        if !status.success() {
            return Err("clone failed".into());
        }
        Command::new("git")
            .args(["-C", tmp.to_str().unwrap(), "sparse-checkout", "set", "tree-sitter-neve"])
            .status()
            .ok();
    }
    Ok(tmp.join("tree-sitter-neve"))
}
