[package]
name = "neve-lsp"
description = "Language Server Protocol implementation for Neve"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
neve-common = { version = "4.0.2", path = "../neve-common" }
neve-diagnostic = { version = "4.0.2", path = "../neve-diagnostic" }
neve-hir = { version = "4.0.2", path = "../neve-hir" }
neve-lexer = { version = "4.0.2", path = "../neve-lexer" }
neve-syntax = { version = "4.0.2", path = "../neve-syntax" }
neve-frontend = { version = "4.0.2", path = "../neve-frontend" }
neve-fmt = { version = "4.0.2", path = "../neve-fmt" }
neve-parser = { version = "4.0.2", path = "../neve-parser" }
neve-typeck = { version = "4.0.2", path = "../neve-typeck" }

tower-lsp.workspace = true
tokio.workspace = true
async-trait.workspace = true
dashmap.workspace = true
serde.workspace = true
serde_json.workspace = true
