[package]
name = "neve-fmt"
description = "Code formatter for the Neve language"
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neve-diagnostic = { version = "4.0.1", path = "../neve-diagnostic" }
neve-syntax = { version = "4.0.1", path = "../neve-syntax" }
neve-parser = { version = "4.0.1", path = "../neve-parser" }

[dev-dependencies]
