[package]
name = "neve-builder"
description = "Sandbox build system for the Neve language"
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neve-derive = { version = "4.0.1", path = "../neve-derive" }
neve-store = { version = "4.0.1", path = "../neve-store" }
neve-fetch = { version = "4.0.1", path = "../neve-fetch" }
thiserror.workspace = true
tempfile.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["sched", "hostname", "resource"] }
libc.workspace = true

[dev-dependencies]
